name: Generate Doxygen documentation and deploy to pages

on:
  push:
  repository_dispatch:
    types: [global-update]

jobs:
  docs:
    permissions:
      pages: write
      id-token: write
    uses: ft-spellbook/doxygen-global/.github/workflows/doxygen-pages.yml@master
    with:
      name: "ft-spellbook"
      brief: "Hivers V Documentation & Resource Sharing"
      extract_static: NO